# Generated by Django 3.2.12 on 2022-09-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='twitter_tweets',
            new_name='twitter_tweet',
        ),
    ]
