# Generated by Django 3.2.12 on 2022-09-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets_analysis', '0002_rename_twitter_tweets_twitter_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweets_text', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='twitter_tweet',
        ),
    ]
