# Generated by Django 3.2.12 on 2022-09-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets_analysis', '0003_auto_20220914_1001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job',
            new_name='text1',
        ),
        migrations.RenameField(
            model_name='text1',
            old_name='tweets_text',
            new_name='tweet_text',
        ),
    ]
