# Generated by Django 3.2.12 on 2022-09-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets_analysis', '0006_alter_text1_tweet_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='tata_tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.CharField(max_length=512)),
                ('tweet_text', models.CharField(max_length=512)),
                ('location', models.CharField(max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='text1',
        ),
    ]
