# Generated by Django 3.2.12 on 2022-11-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets_analysis', '0010_zconnect_tweets'),
    ]

    operations = [
        migrations.CreateModel(
            name='sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neutral', models.IntegerField(default=0)),
                ('positive', models.IntegerField(default=0)),
                ('negative', models.IntegerField(default=0)),
            ],
        ),
    ]
