# Generated by Django 3.2.12 on 2022-11-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets_analysis', '0011_sentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_accuracy_complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_accuracy', models.IntegerField(default=0)),
                ('complaints', models.IntegerField(default=0)),
            ],
        ),
    ]
