# Generated by Django 3.2.12 on 2022-11-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets_analysis', '0012_model_accuracy_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_accuracy_complaints',
            name='model_accuracy',
            field=models.FloatField(default=0),
        ),
    ]
